name: WakaTime Readme

on:
  schedule:
    - cron: '0 22 * * *'
  workflow_dispatch:

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - uses: athul/waka-readme@59f35b046b403338ac2c29161a038e315b5d1192
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API }}
          COMMIT_MESSAGE: Update Wakapi stats
          BLOCKS: "⬜🟨🟩"
          SHOW_TIME: true
          SHOW_TOTAL: true
